### ISSUE TITLE
The result on DiDeMo dataset

### ISSUE THREAD

**Issue by zhenzhiwang** [JaywongWang/TGN#13]
Hi there,

Thank you for sharing the code of your great work! I notice that the paper also reports the performance on the DiDeMo dataset. Could you please include the feature of DiDeMo dataset in this repo so that I can reproduce the result on this dataset?

Thank you a lot.

**Comment by JaywongWang** [comment]
You may find the features from the DiDeMo official repo: https://github.com/LisaAnne/LocalizingMoments

**Comment by JaywongWang** [comment]
> Hi there,
> 
> Thank you for sharing the code of your great work! I notice that the paper also reports the performance on the DiDeMo dataset. Could you please include the feature of DiDeMo dataset in this repo so that I can reproduce the result on this dataset?
> 
> Thank you a lot.

I noticed that the official link is not accessible now. You may also download the features here: https://pan.baidu.com/s/1DvBILOpEnIpuLk3JrzBKSg (code: kuds)

**Comment by zhenzhiwang** [comment]
> > Hi there,
> > Thank you for sharing the code of your great work! I notice that the paper also reports the performance on the DiDeMo dataset. Could you please include the feature of DiDeMo dataset in this repo so that I can reproduce the result on this dataset?
> > Thank you a lot.
> 
> I noticed that the official link is not accessible now. You may also download the features here: https://pan.baidu.com/s/1DvBILOpEnIpuLk3JrzBKSg (code: kuds)

Thank you for sharing this download link. Sorry for the imprecise question raised initially, actually I want to know could you share the dataset code for DiDeMo dataset so that I can directly reproduce the result? Because I notice that the dataset fold only contains the dataloader code for three dataset, excluding DiDeMo dataset.

**Comment by JaywongWang** [comment]
> > > Hi there,
> > > Thank you for sharing the code of your great work! I notice that the paper also reports the performance on the DiDeMo dataset. Could you please include the feature of DiDeMo dataset in this repo so that I can reproduce the result on this dataset?
> > > Thank you a lot.
> > 
> > 
> > I noticed that the official link is not accessible now. You may also download the features here: https://pan.baidu.com/s/1DvBILOpEnIpuLk3JrzBKSg (code: kuds)
> 
> Thank you for sharing this download link. Sorry for the imprecise question raised initially, actually I want to know could you share the dataset code for DiDeMo dataset so that I can directly reproduce the result? Because I notice that the dataset fold only contains the dataloader code for three dataset, excluding DiDeMo dataset.

This is a re-implementation of the original paper, and I am not the author of the TGN paper. I had not written the codes for DiDeMo dataset.

**Comment by zhenzhiwang** [comment]
I see, thank you for the kind reply. By the way, I cannot find the official implementation of this paper, could you please give me some sources?

**Comment by JaywongWang** [comment]
> I see, thank you for the kind reply. By the way, I cannot find the official implementation of this paper, could you please give me some sources?

I have also not found the official implementation.
